package sioet.ui;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.stage.Stage;
import sioet.SioetException;
import sioet.command.Command;
import sioet.command.Parser;
import sioet.storage.Storage;
import sioet.task.TaskList;

/**
 * The main application class for Sioet.
 */
public class Sioet extends Application {

    private static final Storage storage = new Storage();
    private static final TaskList tasks = storage.load();
    private static final Ui ui = new Ui();
    private boolean lastResponseWasError;

    /**
     * Starts the JavaFX GUI.
     *
     * @param stage the main JavaFX stage
     */
    @Override
    public void start(Stage stage) {
        try {
            FXMLLoader fxmlLoader =
                    new FXMLLoader(getClass().getResource("/view/MainWindow.fxml"));

            Scene scene = new Scene(fxmlLoader.load());

            MainWindow mainWindow = fxmlLoader.getController();
            mainWindow.setSioet(this);

            stage.setScene(scene);
            stage.setTitle("Sioet");
            stage.show();

        } catch (Exception exception) {
            exception.printStackTrace();
        }
    }

    /**
     * Starts the command-line version of sioet.
     *
     * @param args command-line arguments, which are not used
     */
    public static void main(String[] args) {
        ui.showWelcome();

        while (true) {
            String command = ui.readCommand();

            if (command == null) {
                break;
            }

            try {
                Command parsedCommand = Parser.parse(command);
                parsedCommand.execute(tasks, ui, storage);

                if (parsedCommand.isExit()) {
                    break;
                }
            } catch (SioetException exception) {
                ui.showError(exception.getMessage());
            }
        }
    }

    /**
     * Processes one command from the GUI.
     *
     * @param command the command entered by the user
     * @return the response generated by sioet
     */
    public String getResponse(String command) {
        try {
            Command parsedCommand = Parser.parse(command);
            parsedCommand.execute(tasks, ui, storage);

            lastResponseWasError = false;
            return ui.getLastResponse();

        } catch (SioetException exception) {
            ui.showError(exception.getMessage());
            lastResponseWasError = true;
            return ui.getLastResponse();
        }
    }

    /**
     * Checks whether the last GUI response was an error.
     *
     * @return true if the last response was an error
     */
    public boolean wasLastResponseAnError() {
        return lastResponseWasError;
    }
}
