package sioet.ui;

import java.util.List;
import java.util.Scanner;

import sioet.task.Task;
import sioet.task.TaskList;

/**
 * Handles interactions between sioet.ui.Sioet and the user.
 */
public class Ui {
    private static final String BLUE = "\u001B[34m";
    private static final String GREEN = "\u001B[32m";
    private static final String RESET = "\u001B[0m";

    private final Scanner scanner;
    private String lastResponse = "";

    /**
     * Creates a user interface that reads commands from standard input.
     */
    public Ui() {
        scanner = new Scanner(System.in);
    }

    /**
     * Returns the most recent response generated by the UI.
     *
     * @return the most recent response
     */
    public String getLastResponse() {
        return lastResponse;
    }

    private void showResponse() {
        System.out.println(BLUE + lastResponse + RESET);
    }

    /**
     * Displays the welcome message and banner to the user.
     */
    public void showWelcome() {
        String horizontalBorder = "═".repeat(30);
        String banner = "╔" + horizontalBorder + "╗\n"
                + "║%-30s║%n".formatted("      ✦       ･        ✧")
                + bannerLine("   :    ", "╔═╗╦╔═╗╔═╗╔╦╗", "    *")
                + bannerLine("  ﾟ     ", "╚═╗║║ ║║╣  ║", "      ✦")
                + bannerLine("     ✧  ", "╚═╝╩╚═╝╚═╝ ╩", "   ･")
                + "║%-30s║%n".formatted("   *        :       ﾟ     ✧")
                + "╚" + horizontalBorder + "╝\n";

        lastResponse = "Hello! I'm sioet.ui.Sioet.\n"
                + "What can I do for you?";

        System.out.println(banner);
        showResponse();
    }

    private String bannerLine(String prefix, String lettering, String suffix) {
        String content = prefix + lettering + suffix;
        return "║" + prefix + BLUE + lettering + RESET + suffix
                + " ".repeat(30 - content.length()) + "║\n";
    }

    /**
     * Reads the next command entered by the user.
     *
     * @return the command entered by the user, or null if there is no input
     */
    public String readCommand() {
        System.out.print(GREEN + "You: " + RESET);
        System.out.flush();

        if (!scanner.hasNextLine()) {
            return null;
        }

        return scanner.nextLine();
    }

    /**
     * Displays the goodbye message to the user.
     */
    public void showBye() {
        lastResponse = "Bye! Hope to see you again soon!";
        showResponse();
    }

    /**
     * Displays an error message to the user.
     *
     * @param message the error message to display
     */
    public void showError(String message) {
        lastResponse = "I couldn't do that: " + message;
        showResponse();
    }

    /**
     * Displays a confirmation that a task was added.
     *
     * @param task the task that was added
     * @param taskCount the number of tasks currently in the list
     */
    public void showTaskAdded(Task task, int taskCount) {
        lastResponse = "Got it. I've added this task:\n  " + task
                + "\nNow you have " + taskCount + " tasks in the list.";
        showResponse();
    }

    /**
     * Displays a confirmation that tasks were deleted.
     *
     * @param deletedTasks the tasks that were deleted
     * @param numberOfDeletedTasks the number of tasks deleted
     * @param taskCount the number of tasks remaining
     */
    public void showTasksDeleted(String deletedTasks,
                                 int numberOfDeletedTasks,
                                 int taskCount) {
        String message = numberOfDeletedTasks == 1
                ? "Noted. I've removed this task:\n\n"
                : "Noted. I've removed these tasks:\n\n";

        lastResponse = message
                + deletedTasks.trim()
                + "\nNow you have "
                + taskCount
                + " tasks in the list.";

        showResponse();
    }

    /**
     * Displays all tasks in the task list.
     *
     * @param tasks the list of tasks to display
     */
    public void showTasks(TaskList tasks) {
        StringBuilder response = new StringBuilder(
                "Here are the tasks in your list:\n");

        for (int index = 0; index < tasks.size(); index++) {
            response.append(index + 1)
                    .append(".")
                    .append(tasks.get(index))
                    .append("\n");
        }

        lastResponse = response.toString().trim();

        showResponse();
    }

    /**
     * Displays tasks matching a search query.
     *
     * @param matchingTasks the matching tasks to display
     */
    public void showMatchingTasks(List<Task> matchingTasks) {
        if (matchingTasks.isEmpty()) {
            lastResponse = "No matching tasks found.";
            System.out.println(BLUE + lastResponse + RESET);
            return;
        }

        StringBuilder response = new StringBuilder(
                "Here are the matching tasks in your list:\n");

        for (int index = 0; index < matchingTasks.size(); index++) {
            response.append(index + 1)
                    .append(".")
                    .append(matchingTasks.get(index))
                    .append("\n");
        }

        lastResponse = response.toString().trim();

        showResponse();
    }

    /**
     * Displays a confirmation that tasks were marked or unmarked.
     *
     * @param markedTasks the tasks that were marked or unmarked
     * @param numberOfMarkedTasks the number of tasks affected
     * @param shouldMarkDone whether the tasks were marked as done
     */
    public void showTasksMarked(String markedTasks,
                                int numberOfMarkedTasks,
                                boolean shouldMarkDone) {
        String message;

        if (numberOfMarkedTasks == 1) {
            message = shouldMarkDone
                    ? "Nice! I've marked this task as done:\n\n"
                    : "OK, I've marked this task as not done yet:\n\n";
        } else {
            message = shouldMarkDone
                    ? "Nice! I've marked these tasks as done:\n\n"
                    : "OK, I've marked these tasks as not done yet:\n\n";
        }

        lastResponse = message + markedTasks.trim();

        showResponse();
    }
}
